In [5]:
#Variable
weight = 64
height = 11.5


In [8]:
#Calculating BMI
bmi = weight//(height*height)
print(bmi)

5.0


In [17]:
z = "GOA to Leh"

In [31]:
rightAlign =  z.rjust(100)
leftAlign = z.ljust(100)
centerAlign = z.center(100)
print(leftAlign.rstrip())
print(rightAlign.lstrip())
print(centerAlign.strip())

GOA to Leh
GOA to Leh
GOA to Leh


z[2:5]

In [ ]:
z[-9:-5]

In [ ]:
String Operations

In [32]:
day1 = "R class in the morning"
day2 = "Python"

In [33]:
today  = "I had " + day1 + " and " + day2
print(today)
print(len(today))
print(day1.lower())
print(day2.upper())
print(today.capitalize())
print(today.title())
newday = day1.rjust(30) + day2.ljust(30) + today.center(60)
print(newday)
newday.replace("R","Python")
newday.replace("Py","@")
print(day2[-3:])
day1[2:]
day2 = day2 + " " + day1[2:]
print(day2)
day2[-12:-7]

I had R class in the morning and Python
39
r class in the morning
PYTHON
I had r class in the morning and python
I Had R Class In The Morning And Python
        R class in the morningPython                                  I had R class in the morning and Python           
hon
Python class in the morning


' the '

Tuples:
* Tuple is like a list but it is immutable(cannot be changed)0
* Tuple uses parenthesis

In [27]:
x  = [[1,2,3,4],3, 5]
print(len(x))
y=[6,7,8]
#x[0][1:4] = [5,6,7,8,9]
x += y
print(len(x))

3
6


In [49]:
emp_id = [1,2,3,4]
emp_name = ["Raj","Sammy","Zeba","Rahul"]
emp_num = 4
emp_age = [40,35,45,30]

In [50]:
emp_list = [emp_id,emp_name,emp_num]
emp_list[0].append(5)
emp_list[1].append("Noman")
emp_list.append(emp_age)
print(emp_list)

[[1, 2, 3, 4, 5], ['Raj', 'Sammy', 'Zeba', 'Rahul', 'Noman'], 4, [40, 35, 45, 30]]


In [5]:
type(x)

list

In [ ]:
7/3

In [ ]:
d = {"Shahrukh","Salman","John","Salman",5,(1,2,3)}
d

In [ ]:
d["producer"] = ("Sajid","Himesh")
d

In [ ]:
d["producer"] = "Ramy"
d

In [ ]:
for i in d:
    print(i)
    print(type(i))

In [ ]:
c = 1,2,3
b = c
c = 1,2,4

In [ ]:
x = 4
y = 8
print(x + y)

Combine dict_values

In [ ]:
d_list = [{"a":2, "b":3, "c":5},
          {"a":7, "b":4, "c":9},
          {"a":5, "d":7, "c":1}]

In [ ]:
def my_fun(a_list):
    result = {}
    for i in a_list:
        print(i)
        print(type(i))
        for k,v in i.items():
            print("if key is : '" + str(k) + "' Value is :" + str(v))
            if k in result:
                result[k] += v
            else:
                result[k] = v
    return result

In [ ]:
my_fun(d_list)

Get_average_report

In [ ]:
reports  = ["Anna, 50, 92, 80", "Bill, 60, 70", "Cal, 98.5,100,95.5,98"]

In [ ]:
def get_avg(a_list):
    result = []
    for i in a_list:
        grades = i.split(",")[1:]
        new_list = [float(i) for i in grades]
        avg = sum(new_list)/len(new_list)
        result.append(avg)        
    return result

In [ ]:
get_avg(reports)

Sum of Digits

In [ ]:
def sumDigit(num):
    sum = 0
    num = str(num)
    if len(new_num) == 1:
        sum += int(new_num)
        return sum
    else:
        return sumDigit(num/10)
    return sum

sumDigit(1234)

In [ ]:
fas = ["10", "30", "5"]
new_list = list(map(float,fas))
F = list(map(lambda x: x/5,new_list))
print(F)

list(filter(lambda x: x%2 ==0, range(0,100)))

In [ ]:
def sumD(num):
    if num < 10:
        return num
    result = 0
    num = str(num)
    for i in num:
        result += int(i)
    
    return sumD(result)

sumD(2323424321)

In [ ]:
a_list = [1,1,1,0,1,0,1,1,0,1,1,1,1,0]

In [ ]:
lambda x, x.split                

Swap largest element with last element

In [ ]:
def swapL(a_list):
    m = a_list.index(max(a_list))
    print(m)
    #l = a_list.index(a_list[-1])
    #print(l)
    temp = a_list[-1]
    a_list[-1] = a_list[m]
    a_list[m] = temp
    
    return a_list



In [ ]:
def remDup(a_list):
    return list(set(a_list))

In [ ]:
newList = [2,3,9,4,5,10,1,6,2]
remDup(a_list)

In [ ]:
#Defining a class


class Circle:
    def __init__(self,radius=5):
        self.r = radius
    
    def area(self):
        self.a  = self.r**2*3.14
        
        return self.a
    
    def perimeter(self):
        self.p = 2*3.14*self.r
        
        return self.p
    
    def sumr(self):
        return self.a + self.p
    

In [ ]:
c1 = Circle(6)
c2 = Circle(4)
print(c1.area(), c1.perimeter())
print(c2.area(), c2.perimeter())
print(c1.sumr(), c2.sumr())

In [ ]:
import math

class Point:
    
    def __init__(self,x,y):
        '''Defines x and y variables'''
        self.X = x
        self.Y = y
    
    # Calculating length
    
    def length(self):
        return(math.sqrt(self.X**2 + self.Y**2))
    
    # Calculating Distance
    def distance(self,other):
        dx = self.X - other.X
        dy = self.Y - other.Y
        return(math.sqrt(dx**2 + dy**2))
    
    

In [ ]:
point1 = Point(4,5)
point2 = Point(2,3)
point1 = Circle(3)
print(point1.X,point2.Y)
print(point1.length())
print(point2.length())
print(point1.distance(point2))

In [ ]:
pip install numpy

In [1]:
import numpy as np

In [39]:
arr = np.array([[1,2.,3,4],
              [5,6,7,8],
                [11,12,13,15]]).reshape(4,3)

type(arr)

numpy.ndarray

In [26]:
arr.reshape(12,)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 11., 12., 13., 15.])

In [41]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., 11.],
       [12., 13., 15.]])

In [45]:
arr[:,1:3]

array([[ 2.,  3.],
       [ 5.,  6.],
       [ 8., 11.],
       [13., 15.]])

In [36]:
temp.dtype

dtype('int64')